name: alcfai
channels:
  - defaults
  - conda-forge
  - openbabel
dependencies:
  - python>3.7
  - numpy>1.19
  - pandas==1.*
  - scikit-learn>0.23
  - matplotlib>3
  - openbabel==2.4.*
  - rdkit==2020.03.*
  - mordred==1.2.*
  - tqdm
  - jupyterlab
